import { HttpStatus } from '@nestjs/common';

/**
 * 도메인별 커스텀 에러 코드가 없을 때 사용하는 HTTP 상태코드 기반 폴백 코드.
 * 실제 사용처: HttpExceptionFilter의 `body.code ?? getCommonErrorCode(statusCode)`
 */
export const COMMON_ERROR_CODES = {
  BAD_REQUEST: 'COMMON400',
  UNAUTHORIZED: 'AUTH401', // 인증 관련은 AUTH prefix로 구분 (의도적)
  FORBIDDEN: 'COMMON403',
  NOT_FOUND: 'COMMON404',
  METHOD_NOT_ALLOWED: 'COMMON405',
  REQUEST_TIMEOUT: 'COMMON408',
  CONFLICT: 'COMMON409',
  PAYLOAD_TOO_LARGE: 'COMMON413',
  UNSUPPORTED_MEDIA_TYPE: 'COMMON415',
  UNPROCESSABLE_ENTITY: 'COMMON422',
  TOO_MANY_REQUESTS: 'COMMON429',
  INTERNAL_SERVER_ERROR: 'COMMON500',
  BAD_GATEWAY: 'COMMON502',
  SERVICE_UNAVAILABLE: 'COMMON503',
  GATEWAY_TIMEOUT: 'COMMON504',
} as const;

export type CommonErrorCode = (typeof COMMON_ERROR_CODES)[keyof typeof COMMON_ERROR_CODES];

const STATUS_TO_CODE: Partial<Record<number, CommonErrorCode>> = {
  [HttpStatus.BAD_REQUEST]: COMMON_ERROR_CODES.BAD_REQUEST,
  [HttpStatus.UNAUTHORIZED]: COMMON_ERROR_CODES.UNAUTHORIZED,
  [HttpStatus.FORBIDDEN]: COMMON_ERROR_CODES.FORBIDDEN,
  [HttpStatus.NOT_FOUND]: COMMON_ERROR_CODES.NOT_FOUND,
  [HttpStatus.METHOD_NOT_ALLOWED]: COMMON_ERROR_CODES.METHOD_NOT_ALLOWED,
  [HttpStatus.REQUEST_TIMEOUT]: COMMON_ERROR_CODES.REQUEST_TIMEOUT,
  [HttpStatus.CONFLICT]: COMMON_ERROR_CODES.CONFLICT,
  [HttpStatus.PAYLOAD_TOO_LARGE]: COMMON_ERROR_CODES.PAYLOAD_TOO_LARGE,
  [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: COMMON_ERROR_CODES.UNSUPPORTED_MEDIA_TYPE,
  [HttpStatus.UNPROCESSABLE_ENTITY]: COMMON_ERROR_CODES.UNPROCESSABLE_ENTITY,
  [HttpStatus.TOO_MANY_REQUESTS]: COMMON_ERROR_CODES.TOO_MANY_REQUESTS,
  [HttpStatus.BAD_GATEWAY]: COMMON_ERROR_CODES.BAD_GATEWAY,
  [HttpStatus.SERVICE_UNAVAILABLE]: COMMON_ERROR_CODES.SERVICE_UNAVAILABLE,
  [HttpStatus.GATEWAY_TIMEOUT]: COMMON_ERROR_CODES.GATEWAY_TIMEOUT,
};

export const getCommonErrorCode = (statusCode: number): CommonErrorCode =>
  STATUS_TO_CODE[statusCode] ?? COMMON_ERROR_CODES.INTERNAL_SERVER_ERROR;
